package codegen

import (
	"encoding/json"
	"fmt"
	"hash/fnv"
	"regexp"
	"sort"
	"strings"

	"github.com/yfernando/esp32-layout-designer/models"
)

func sanitizeName(name string) string {
	re := regexp.MustCompile(`[^a-zA-Z0-9]`)
	cleaned := re.ReplaceAllString(name, "")
	if cleaned == "" {
		return "Custom"
	}
	first := cleaned[0]
	if first >= '0' && first <= '9' {
		return "Custom" + cleaned
	}
	return cleaned
}

func commentName(name string) string {
	name = strings.ReplaceAll(name, "\r", " ")
	name = strings.ReplaceAll(name, "\n", " ")
	return name
}

func layoutFingerprint(layout *models.Layout) uint32 {
	payload, err := json.Marshal(layout)
	if err != nil {
		payload = []byte(layout.Name)
	}
	h := fnv.New32a()
	_, _ = h.Write(payload)
	return h.Sum32()
}

func resolveColor(color string) string {
	themeColors := map[string]bool{
		"themeBg": true, "themeHeader": true, "themePanel": true, "themeEdge": true,
		"themeText": true, "themeTextMuted": true, "themeAccent": true, "themeGood": true,
	}
	if themeColors[color] {
		return color
	}
	if color == "none" || color == "transparent" || color == "" {
		return "themeBg"
	}
	if len(color) == 7 && color[0] == '#' {
		r := hexToInt(color[1:3])
		g := hexToInt(color[3:5])
		b := hexToInt(color[5:7])
		return fmt.Sprintf("tft.color565(%d, %d, %d)", r, g, b)
	}
	return "themeText"
}

func hexToInt(hex string) int {
	val := 0
	for _, c := range strings.ToLower(hex) {
		val *= 16
		if c >= '0' && c <= '9' {
			val += int(c - '0')
		} else if c >= 'a' && c <= 'f' {
			val += int(c-'a') + 10
		}
	}
	return val
}

func getPropStr(props map[string]interface{}, key, def string) string {
	if v, ok := props[key]; ok {
		if s, ok := v.(string); ok {
			return s
		}
	}
	return def
}

func getPropInt(props map[string]interface{}, key string, def int) int {
	if v, ok := props[key]; ok {
		switch n := v.(type) {
		case float64:
			return int(n)
		case int:
			return n
		}
	}
	return def
}

func alignToDatum(align string, x int, width int) (datum string, drawX int) {
	switch align {
	case "center":
		return "TC_DATUM", x + width/2
	case "right":
		return "TR_DATUM", x + width
	default:
		return "TL_DATUM", x
	}
}

func getPropBool(props map[string]interface{}, key string, def bool) bool {
	if v, ok := props[key]; ok {
		switch b := v.(type) {
		case bool:
			return b
		}
	}
	return def
}

func GenerateLayoutCpp(layout *models.Layout) string {
	prefix := sanitizeName(layout.Name)
	p := strings.ToLower(prefix[:1]) + prefix[1:]
	displayName := escapeStr(layout.Name)
	commentDisplayName := commentName(layout.Name)
	fingerprint := layoutFingerprint(layout)

	// Separate elements by function
	var timeEls, weatherEls []models.Element
	for _, el := range layout.Elements {
		switch el.Type {
		case "time", "date":
			timeEls = append(timeEls, el)
		default:
			weatherEls = append(weatherEls, el)
		}
	}

	// Sort by zIndex
	sort.Slice(weatherEls, func(i, j int) bool { return weatherEls[i].ZIndex < weatherEls[j].ZIndex })
	sort.Slice(timeEls, func(i, j int) bool { return timeEls[i].ZIndex < timeEls[j].ZIndex })

	var sb strings.Builder

	// File header
	sb.WriteString(`#include <TFT_eSPI.h>
#include "DisplayCommon.h"
#include "DisplayLayout.h"
#include "WeatherTypes.h"

// Auto-generated layout: ` + commentDisplayName + `
// Generated by ESP32 Layout Designer

const bool hasGeneratedCustomLayout = true;
const uint32_t generatedCustomLayoutFingerprint = 0x` + fmt.Sprintf("%08X", fingerprint) + `;

`)

	// Refresh indicator (standard 8-dot spinner)
	sb.WriteString(fmt.Sprintf(`static void %sDrawRefreshIndicator(TFT_eSPI &tft, bool active, uint8_t frame) {
  const int cx = %d;
  const int cy = 14;
  const int r = 7;
  static const int8_t dx[8] = {0, 4, 6, 4, 0, -4, -6, -4};
  static const int8_t dy[8] = {-6, -4, 0, 4, 6, 4, 0, -4};
  tft.fillCircle(cx, cy, r + 2, themeHeader);
  tft.drawCircle(cx, cy, r, themeEdge);
  if (!active) return;
  for (int i = 0; i < 8; ++i) {
    uint16_t c = (i == frame) ? themeAccent : themeTextMuted;
    tft.fillCircle(cx + dx[i], cy + dy[i], (i == frame) ? 2 : 1, c);
  }
}

`, p, layout.Width-17))

	// DrawNowAndDate
	sb.WriteString(fmt.Sprintf("static void %sDrawNowAndDate(TFT_eSPI &tft) {\n", p))
	for _, el := range timeEls {
		renderElement(&sb, el, false)
	}
	sb.WriteString("}\n\n")

	// DrawHeader
	sb.WriteString(fmt.Sprintf(`static void %sDrawHeader(TFT_eSPI &tft) {
  tft.fillScreen(%s);
  tft.fillRect(0, 0, tft.width(), 28, themeHeader);
  tft.setTextDatum(TL_DATUM);
  tft.drawFastHLine(0, 28, tft.width(), themeEdge);
  %sDrawNowAndDate(tft);
  %sDrawRefreshIndicator(tft, refreshAnimating, spinnerFrame);
}

`, p, resolveColor(layout.BackgroundColor), p, p))

	// DrawStatus
	sb.WriteString(fmt.Sprintf(`static void %sDrawStatus(TFT_eSPI &tft, const String &status, const String &detail) {
  %sDrawHeader(tft);
  tft.setTextColor(themeAccent, %s);
  tft.drawString(status, 8, 54, 2);
  tft.setTextColor(themeText, %s);
  tft.drawString(detail, 8, 84, 2);
}

`, p, p, resolveColor(layout.BackgroundColor), resolveColor(layout.BackgroundColor)))

	// DrawWeather
	sb.WriteString(fmt.Sprintf("static void %sDrawWeather(TFT_eSPI &tft, const WeatherData &w) {\n", p))
	sb.WriteString(fmt.Sprintf("  %sDrawHeader(tft);\n\n", p))
	for _, el := range weatherEls {
		renderElement(&sb, el, true)
	}
	sb.WriteString(fmt.Sprintf("\n  %sDrawNowAndDate(tft);\n", p))
	sb.WriteString("}\n\n")

	// LayoutFunctions struct
	rotation := layout.Rotation
	sb.WriteString(fmt.Sprintf(`const LayoutFunctions layoutCustomGenerated = {
  %sDrawWeather,
  %sDrawHeader,
  %sDrawNowAndDate,
  %sDrawStatus,
  %sDrawRefreshIndicator,
  "%s",
  %d // %s
};
`, p, p, p, p, p, displayName, rotation, layout.Orientation))

	return sb.String()
}

func renderElement(sb *strings.Builder, el models.Element, hasWeatherData bool) {
	props := el.Properties
	switch el.Type {
	case "data-text":
		if !hasWeatherData {
			return
		}
		field := getPropStr(props, "dataField", "airTempC")
		font := getPropInt(props, "font", 2)
		textSize := getPropInt(props, "textSize", 1)
		color := resolveColor(getPropStr(props, "color", "themeText"))
		bgColor := resolveColor(getPropStr(props, "bgColor", "themeBg"))
		prefix := getPropStr(props, "prefix", "")
		suffix := getPropStr(props, "suffix", "")
		align := getPropStr(props, "align", "left")

		datum, drawX := alignToDatum(align, el.X, el.Width)
		if datum != "TL_DATUM" {
			sb.WriteString(fmt.Sprintf("  tft.setTextDatum(%s);\n", datum))
		}
		sb.WriteString(fmt.Sprintf("  tft.setTextColor(%s, %s);\n", color, bgColor))
		if textSize > 1 {
			sb.WriteString(fmt.Sprintf("  tft.setTextSize(%d);\n", textSize))
		}

		expr := "w." + field
		if prefix != "" || suffix != "" {
			parts := []string{}
			if prefix != "" {
				parts = append(parts, fmt.Sprintf(`"%s"`, escapeStr(prefix)))
			}
			parts = append(parts, expr)
			if suffix != "" {
				if suffix == "\u00B0" {
					parts = append(parts, `String((char)0xB0)`)
				} else {
					parts = append(parts, fmt.Sprintf(`"%s"`, escapeStr(suffix)))
				}
			}
			expr = strings.Join(parts, " + ")
		}

		sb.WriteString(fmt.Sprintf("  tft.drawString(%s, %d, %d, %d);\n", expr, drawX, el.Y, font))
		if textSize > 1 {
			sb.WriteString("  tft.setTextSize(1);\n")
		}
		if datum != "TL_DATUM" {
			sb.WriteString("  tft.setTextDatum(TL_DATUM);\n")
		}
		sb.WriteString("\n")

	case "static-text":
		text := getPropStr(props, "text", "Label")
		font := getPropInt(props, "font", 2)
		textSize := getPropInt(props, "textSize", 1)
		color := resolveColor(getPropStr(props, "color", "themeText"))
		bgColor := resolveColor(getPropStr(props, "bgColor", "themeBg"))
		align := getPropStr(props, "align", "left")

		datum, drawX := alignToDatum(align, el.X, el.Width)
		if datum != "TL_DATUM" {
			sb.WriteString(fmt.Sprintf("  tft.setTextDatum(%s);\n", datum))
		}
		sb.WriteString(fmt.Sprintf("  tft.setTextColor(%s, %s);\n", color, bgColor))
		if textSize > 1 {
			sb.WriteString(fmt.Sprintf("  tft.setTextSize(%d);\n", textSize))
		}
		sb.WriteString(fmt.Sprintf(`  tft.drawString("%s", %d, %d, %d);`+"\n", escapeStr(text), drawX, el.Y, font))
		if textSize > 1 {
			sb.WriteString("  tft.setTextSize(1);\n")
		}
		if datum != "TL_DATUM" {
			sb.WriteString("  tft.setTextDatum(TL_DATUM);\n")
		}
		sb.WriteString("\n")

	case "rect", "rounded-rect":
		fillColor := resolveColor(getPropStr(props, "fillColor", "themePanel"))
		strokeColor := getPropStr(props, "strokeColor", "themeEdge")
		radius := getPropInt(props, "cornerRadius", 0)

		if radius > 0 {
			sb.WriteString(fmt.Sprintf("  tft.fillRoundRect(%d, %d, %d, %d, %d, %s);\n", el.X, el.Y, el.Width, el.Height, radius, fillColor))
			if strokeColor != "none" && strokeColor != "transparent" {
				sb.WriteString(fmt.Sprintf("  tft.drawRoundRect(%d, %d, %d, %d, %d, %s);\n", el.X, el.Y, el.Width, el.Height, radius, resolveColor(strokeColor)))
			}
		} else {
			sb.WriteString(fmt.Sprintf("  tft.fillRect(%d, %d, %d, %d, %s);\n", el.X, el.Y, el.Width, el.Height, fillColor))
			if strokeColor != "none" && strokeColor != "transparent" {
				sb.WriteString(fmt.Sprintf("  tft.drawRect(%d, %d, %d, %d, %s);\n", el.X, el.Y, el.Width, el.Height, resolveColor(strokeColor)))
			}
		}
		sb.WriteString("\n")

	case "hline":
		color := resolveColor(getPropStr(props, "color", "themeEdge"))
		sb.WriteString(fmt.Sprintf("  tft.drawFastHLine(%d, %d, %d, %s);\n\n", el.X, el.Y, el.Width, color))

	case "vline":
		color := resolveColor(getPropStr(props, "color", "themeEdge"))
		sb.WriteString(fmt.Sprintf("  tft.drawFastVLine(%d, %d, %d, %s);\n\n", el.X, el.Y, el.Height, color))

	case "weather-icon":
		if !hasWeatherData {
			return
		}
		size := getPropInt(props, "iconSize", 48)
		sb.WriteString(fmt.Sprintf("  drawWeatherIcon(tft, %d, %d, %d, w.currentIconCode);\n\n", el.X, el.Y, size))

	case "forecast-card":
		if !hasWeatherData {
			return
		}
		cw := getPropInt(props, "cardWidth", 76)
		ch := getPropInt(props, "cardHeight", 58)
		sp := getPropInt(props, "cardSpacing", 2)
		cr := getPropInt(props, "cornerRadius", 6)
		cardBg := resolveColor(getPropStr(props, "cardBg", "themePanel"))
		cardBorder := resolveColor(getPropStr(props, "cardBorder", "themeEdge"))
		labelColor := resolveColor(getPropStr(props, "labelColor", "themeAccent"))
		tempColor := resolveColor(getPropStr(props, "tempColor", "themeText"))
		rainColor := resolveColor(getPropStr(props, "rainColor", "themeTextMuted"))

		sb.WriteString(fmt.Sprintf(`  for (int i = 0; i < 3; ++i) {
    int x = %d + i * %d;
    tft.fillRoundRect(x, %d, %d, %d, %d, %s);
    tft.drawRoundRect(x, %d, %d, %d, %d, %s);
    drawWeatherIcon(tft, x + 4, %d + 2, 20, w.nextDayIconCode[i]);
    String label = w.nextDayLabel[i].isEmpty() ? String("D+") + String(i + 1) : w.nextDayLabel[i];
    tft.setTextColor(%s, %s);
    tft.drawString(label, x + 28, %d + 4, 2);
    tft.setTextColor(%s, %s);
    tft.drawString(w.nextDayMinC[i] + "-" + w.nextDayMaxC[i] + String((char)0xB0), x + 6, %d + 24, 2);
    String rain = w.nextDayRainChance[i];
    if (rain.isEmpty() || rain == "--") rain = "";
    String rRange = w.nextDayRain[i];
    String rLine = "";
    if (!rain.isEmpty()) rLine += rain;
    if (!rRange.isEmpty()) { if (!rLine.isEmpty()) rLine += " "; rLine += rRange; }
    if (rLine.isEmpty()) rLine = "--";
    tft.setTextColor(%s, %s);
    tft.drawString(rLine, x + 6, %d + 42, 1);
  }

`, el.X, cw+sp, el.Y, cw, ch, cr, cardBg,
			el.Y, cw, ch, cr, cardBorder,
			el.Y,
			labelColor, cardBg, el.Y,
			tempColor, cardBg, el.Y,
			rainColor, cardBg, el.Y))

	case "time":
		font := getPropInt(props, "font", 2)
		color := resolveColor(getPropStr(props, "color", "themeGood"))
		bgColor := resolveColor(getPropStr(props, "bgColor", "themeHeader"))
		timeFormat := getPropStr(props, "format", "12h")
		showSeconds := getPropBool(props, "showSeconds", true)

		sb.WriteString(fmt.Sprintf("  {\n    tft.fillRect(%d, %d, %d, %d, %s);\n", el.X, el.Y, el.Width, el.Height, bgColor))
		sb.WriteString(fmt.Sprintf("    tft.setTextColor(%s, %s);\n", color, bgColor))

		if timeFormat == "24h" {
			if showSeconds {
				sb.WriteString("    char timeBuf[9];\n")
				sb.WriteString("    struct tm ti; getLocalTime(&ti);\n")
				sb.WriteString("    snprintf(timeBuf, sizeof(timeBuf), \"%02d:%02d:%02d\", ti.tm_hour, ti.tm_min, ti.tm_sec);\n")
			} else {
				sb.WriteString("    char timeBuf[6];\n")
				sb.WriteString("    struct tm ti; getLocalTime(&ti);\n")
				sb.WriteString("    snprintf(timeBuf, sizeof(timeBuf), \"%02d:%02d\", ti.tm_hour, ti.tm_min);\n")
			}
			sb.WriteString(fmt.Sprintf("    tft.drawString(timeBuf, %d, %d, %d);\n  }\n\n", el.X, el.Y, font))
		} else {
			if showSeconds {
				sb.WriteString("    const String timeStr = getCurrentTimeString12h();\n")
			} else {
				sb.WriteString("    String timeStr = getCurrentTimeString12h();\n")
				sb.WriteString("    // Strip seconds: \"H:MM:SS AM\" -> \"H:MM AM\"\n")
				sb.WriteString("    int firstColon = timeStr.indexOf(':');\n")
				sb.WriteString("    int secondColon = timeStr.indexOf(':', firstColon + 1);\n")
				sb.WriteString("    if (secondColon > 0) {\n")
				sb.WriteString("      int space = timeStr.indexOf(' ', secondColon);\n")
				sb.WriteString("      if (space > 0) timeStr = timeStr.substring(0, secondColon) + timeStr.substring(space);\n")
				sb.WriteString("    }\n")
			}
			sb.WriteString(fmt.Sprintf("    tft.drawString(timeStr, %d, %d, %d);\n  }\n\n", el.X, el.Y, font))
		}

	case "date":
		font := getPropInt(props, "font", 2)
		color := resolveColor(getPropStr(props, "color", "themeGood"))
		bgColor := resolveColor(getPropStr(props, "bgColor", "themeHeader"))
		dateFormat := getPropStr(props, "dateFormat", "short")

		sb.WriteString(fmt.Sprintf("  {\n    tft.fillRect(%d, %d, %d, %d, %s);\n", el.X, el.Y, el.Width, el.Height, bgColor))
		sb.WriteString(fmt.Sprintf("    tft.setTextColor(%s, %s);\n", color, bgColor))

		switch dateFormat {
		case "long":
			sb.WriteString("    struct tm ti; getLocalTime(&ti);\n")
			sb.WriteString("    static const char* dayNames[] = {\"Sunday\",\"Monday\",\"Tuesday\",\"Wednesday\",\"Thursday\",\"Friday\",\"Saturday\"};\n")
			sb.WriteString("    static const char* monthNames[] = {\"January\",\"February\",\"March\",\"April\",\"May\",\"June\",\"July\",\"August\",\"September\",\"October\",\"November\",\"December\"};\n")
			sb.WriteString("    char dateBuf[40];\n")
			sb.WriteString("    snprintf(dateBuf, sizeof(dateBuf), \"%s %d %s\", dayNames[ti.tm_wday], ti.tm_mday, monthNames[ti.tm_mon]);\n")
		case "numeric":
			sb.WriteString("    struct tm ti; getLocalTime(&ti);\n")
			sb.WriteString("    char dateBuf[11];\n")
			sb.WriteString("    snprintf(dateBuf, sizeof(dateBuf), \"%02d/%02d/%04d\", ti.tm_mday, ti.tm_mon + 1, ti.tm_year + 1900);\n")
		default:
			sb.WriteString("    const String dateStr = getCurrentDateStringShort();\n")
			sb.WriteString(fmt.Sprintf("    tft.drawString(dateStr, %d, %d, %d);\n  }\n\n", el.X, el.Y, font))
			return
		}
		sb.WriteString(fmt.Sprintf("    tft.drawString(dateBuf, %d, %d, %d);\n  }\n\n", el.X, el.Y, font))
	}
}

func escapeStr(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	s = strings.ReplaceAll(s, "\r", `\r`)
	s = strings.ReplaceAll(s, "\t", `\t`)
	return s
}
