#include <TFT_eSPI.h>
#include "DisplayCommon.h"
#include "DisplayLayout.h"
#include "WeatherTypes.h"

// Auto-generated layout: Minimal Clock
// Generated by ESP32 Layout Designer

static void minimalClockDrawRefreshIndicator(TFT_eSPI &tft, bool active, uint8_t frame) {
  const int cx = 223;
  const int cy = 14;
  const int r = 7;
  static const int8_t dx[8] = {0, 4, 6, 4, 0, -4, -6, -4};
  static const int8_t dy[8] = {-6, -4, 0, 4, 6, 4, 0, -4};
  tft.fillCircle(cx, cy, r + 2, themeHeader);
  tft.drawCircle(cx, cy, r, themeEdge);
  if (!active) return;
  for (int i = 0; i < 8; ++i) {
    uint16_t c = (i == frame) ? themeAccent : themeTextMuted;
    tft.fillCircle(cx + dx[i], cy + dy[i], (i == frame) ? 2 : 1, c);
  }
}

static void minimalClockDrawNowAndDate(TFT_eSPI &tft) {
  {
    const String timeStr = getCurrentTimeString12h();
    tft.fillRect(20, 60, 200, 52, themeBg);
    tft.setTextColor(themeText, themeBg);
    tft.drawString(timeStr, 20, 60, 4);
  }

  {
    const String dateStr = getCurrentDateStringShort();
    tft.fillRect(20, 120, 200, 26, themeBg);
    tft.setTextColor(themeTextMuted, themeBg);
    tft.drawString(dateStr, 20, 120, 4);
  }

}

static void minimalClockDrawHeader(TFT_eSPI &tft) {
  tft.fillScreen(themeBg);
  tft.fillRect(0, 0, tft.width(), 28, themeHeader);
  tft.setTextDatum(TL_DATUM);
  tft.drawFastHLine(0, 28, tft.width(), themeEdge);
  minimalClockDrawNowAndDate(tft);
  minimalClockDrawRefreshIndicator(tft, refreshAnimating, spinnerFrame);
}

static void minimalClockDrawStatus(TFT_eSPI &tft, const String &status, const String &detail) {
  minimalClockDrawHeader(tft);
  tft.setTextColor(themeAccent, themeBg);
  tft.drawString(status, 8, 54, 2);
  tft.setTextColor(themeText, themeBg);
  tft.drawString(detail, 8, 84, 2);
}

static void minimalClockDrawWeather(TFT_eSPI &tft, const WeatherData &w) {
  minimalClockDrawHeader(tft);

  tft.fillRect(0, 0, 240, 320, themeBg);

  tft.drawFastHLine(20, 160, 200, themeEdge);

  tft.setTextColor(themeAccent, themeBg);
  tft.drawString(w.airTempC + String((char)0xB0), 20, 180, 4);

  tft.setTextColor(themeGood, themeBg);
  tft.drawString(w.rainTodayChance, 130, 180, 4);

  tft.setTextColor(themeTextMuted, themeBg);
  tft.drawString(w.stationName, 20, 230, 2);


  minimalClockDrawNowAndDate(tft);
}

const LayoutFunctions layoutCustomMinimalClock = {
  minimalClockDrawWeather,
  minimalClockDrawHeader,
  minimalClockDrawNowAndDate,
  minimalClockDrawStatus,
  minimalClockDrawRefreshIndicator,
  "Minimal Clock",
  0 // portrait
};
