#include <TFT_eSPI.h>
#include "DisplayCommon.h"
#include "DisplayLayout.h"
#include "WeatherTypes.h"

// Auto-generated layout: Test Layout
// Generated by ESP32 Layout Designer

static void testLayoutDrawRefreshIndicator(TFT_eSPI &tft, bool active, uint8_t frame) {
  const int cx = 223;
  const int cy = 14;
  const int r = 7;
  static const int8_t dx[8] = {0, 4, 6, 4, 0, -4, -6, -4};
  static const int8_t dy[8] = {-6, -4, 0, 4, 6, 4, 0, -4};
  tft.fillCircle(cx, cy, r + 2, themeHeader);
  tft.drawCircle(cx, cy, r, themeEdge);
  if (!active) return;
  for (int i = 0; i < 8; ++i) {
    uint16_t c = (i == frame) ? themeAccent : themeTextMuted;
    tft.fillCircle(cx + dx[i], cy + dy[i], (i == frame) ? 2 : 1, c);
  }
}

static void testLayoutDrawNowAndDate(TFT_eSPI &tft) {
}

static void testLayoutDrawHeader(TFT_eSPI &tft) {
  tft.fillScreen(themeBg);
  tft.fillRect(0, 0, tft.width(), 28, themeHeader);
  tft.setTextDatum(TL_DATUM);
  tft.drawFastHLine(0, 28, tft.width(), themeEdge);
  testLayoutDrawNowAndDate(tft);
  testLayoutDrawRefreshIndicator(tft, refreshAnimating, spinnerFrame);
}

static void testLayoutDrawStatus(TFT_eSPI &tft, const String &status, const String &detail) {
  testLayoutDrawHeader(tft);
  tft.setTextColor(themeAccent, themeBg);
  tft.drawString(status, 8, 54, 2);
  tft.setTextColor(themeText, themeBg);
  tft.drawString(detail, 8, 84, 2);
}

static void testLayoutDrawWeather(TFT_eSPI &tft, const WeatherData &w) {
  testLayoutDrawHeader(tft);

  tft.setTextColor(themeAccent, themeBg);
  tft.setTextSize(2);
  tft.drawString(w.airTempC + String((char)0xB0), 14, 58, 4);
  tft.setTextSize(1);


  testLayoutDrawNowAndDate(tft);
}

const LayoutFunctions layoutCustomTestLayout = {
  testLayoutDrawWeather,
  testLayoutDrawHeader,
  testLayoutDrawNowAndDate,
  testLayoutDrawStatus,
  testLayoutDrawRefreshIndicator,
  "Test Layout",
  0 // portrait
};
